name: Automation Tests for production site

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

           # Read Node.js version from .nvmrc
      - name: Read .nvmrc
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      # Use Node.js version from .nvmrc
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      # Install dependencies
      - name: Install Dependencies
        run: npm install
      
      - name: install playwright
        run: npx playwright install

      # Run Playwright Tests
      - name: Run Playwright Tests
        id: playwright
        run: |
          npx playwright test --reporter=html --output=playwright-report

      # Upload Playwright Report
      - uses: actions/upload-artifact@v4
        id: artifact-upload
        if: always()
        with:
          name: playwright-report
          path: playwright-report/